### PR TITLE
stored and referenced image files locally

### PR DESCRIPTION
**Pull request by Koala-t**
I used ImageOptim to decrease the size and loading time of the images.
I also had to convert them from their native jpeg to a png format for them to render correctly.
These steps may have effected the image quality.

### CODE REVIEW

**Comment by juanmnl** [comment]
Cool, is there a visible quality reduction or not? and did you change only the file extension or did you make a real jpeg -> png conversion?

**Comment by Koala-t** [comment]
I just changed the file name to end with png but that was enough to satisfy
the error message that was popping up. I only compared one of the pictures
closely and it seemed okay but for some reason the colors were a touch less
vibrant. Take a look at the page when you get the chance. If you're unhappy
with the pictures I'll try it again without running the optimizer and see
if that makes a difference.

**Comment by juanmnl** [comment]
I took a look and it seems fine. Maybe the lack of vibrance is because of the size (former website is 200x200, current is 250x250 - so images are expanded) There are a couple of workarounds for this, using bigger images or downsizing the format on the current website (which will break the layout).

I'll merge this, as it works fine for now, but it's another thing we should keep track of.

Thanks again for your help, i'll try to work on the webpack file-loader so it doesn't bother when using jpegs.

Cheers!

**Comment by juanmnl** [comment]
We should be able to use jpeg extension now (was only png or jpg before).

:)

**Comment by Koala-t** [comment]
Hey Juan,

I did some poking around in the bulma docs and found their example for
mutually exclusive tab selections which doesn't seem to work so I don't
think its just something were doing wrong.
http://bulma.io/documentation/components/tabs/
Besides using jQuery I haven't found any other methods of toggling the
selectors.
It may be the case that only one tab is selected at a time but the selected
tabs are not being highlighted.
I think ill just move on for now and circle back to this issue.

I have a couple of questions on the other tasks.
As I understand it, you still want:
- media to display based on the selected tab
- a working submission form

Should I store all of the images and videos on Instagram locally in the app
like I did for the other photos?
Which video should I set as the first one to play?

The submission form seems like it is mostly built at this point.
All that needs to be done to allow for input is to delete disable from the
fields.
Are there any security concerns that I should look out for?
Where should I store/post the input data?

Thanks,
Chris

**Comment by juanmnl** [comment]
Hey Chris!
Ok, bulma doesn't have any js, so it wont change alone. We can use jQuery for now, but it's gonna be better to make it pure js with react. You can see an example i made [here.](https://github.com/IncaDevs/incadevs/tree/master/src/components/layout) Checkout the navbar and navbartoggle components.

How well do you know react is the question here?
If not so much, i'd recommend you to follow [the first -free- tutorial](http://www.reactjsprogram.com/) which will give you a better perspective of what i'm talking about. I haven't done it, but i've heard great things about it.

For the files and instagram pics, everything will be pulled from github repos or IG with [Axios](https://github.com/mzabriskie/axios) which is an http client.

For the media files, we need to talk to Michelle, as it would be better to have tem on vimeo or youtube, and just iframe them into the website.

Let me know if you have any other doubts, i'll try to answer as fast as i can.

:)

**Comment by Koala-t** [comment]
Thanks a lot Juanmnl,

Sorry if I came across as accusatory on slack.
I just wanted to let Michelle know where I stand.
Thanks again for letting me help out with this website!

-Chris Johnson

**Pull request merged**
