### PR TITLE
Minor style changes

### PR DESCRIPTION
**Pull request by Koala-t**
There is probably a more DRY way of detecting clicks than putting an onClick() in each list-item.

### CODE REVIEW

**Comment by juanmnl** [comment]
Hey @Koala-t Thanks for your help!
Gonna merge the changes, but we'll need to bring those files to the project as static assets, eventually. I guess there's gonna be a problem when we take down squarespace site. For now it's ok, we just need to remember that.
Same goes for jquery, we should try to use react's synthetic events, but for now it's great.

Thanks again :)

**Comment by Koala-t** [comment]
Hi Juanmnl,

Thanks for letting me help out with the site. I'll try and make these
changes this afternoon.
Is it okay if I make a file containing all of the required images and
media?

-Chris Johnson

**Comment by juanmnl** [comment]
Of course!
Just make a folder under src/assets - images/ and a media/ . I think webpack will inline them if they are small enough (not sure, will look it up later). If you can, download [imageOptim](https://imageoptim.com/) and process the images before pushing them. I'll try to optimise the image processing in webpack later too.

Thanks! :D

**Comment by Koala-t** [comment]
hi Juanmnl,

I did a little more work on the mind-makers website this morning. It wasn't
too hard to add the images to a new folder in the assets folder.
When I try and reference them however (using this method: <Image
source={require('./../../../assets/images/MichelleEaster.png')} />)
I get back an error saying that a method in one if the node_modules is
undefined.

Specifically the inst.render() function on line 587 of
/website/node_modules/react/lib/ReactCompositeComponent.js.
Have you ever run into something like this before?

-Chris

**Comment by Koala-t** [comment]
Holy smokes, I figured it out! woot!

I love it when you step away for a little while then the answer is as clear
as day.

**Pull request merged**
